### ISSUE TITLE
I'm afraid so-remove-wpml-menu-sync don't work with latest WPML plugins

### ISSUE THREAD

**Issue by skeptikas** [senlin/so-remove-wpml-menu-sync#1]
Hello,

I did some small research, tried to adapt your plugin to latest WPML version, they moved menus-sync.php file to separate menu-sync folder, but editing didn't made plugin working. Guess something else was changed too..

best regards,
Mark

**Comment by senlin** [comment]
Hi Mark, thanks for the bug report, will try to make it work again with the latest WPML version.

I would appreciate it if you can share what you tried already.

Cheers,
Piet

**Comment by skeptikas** [comment]
I'm not good in php, but tried some edits:
1.  remove_submenu_page('sitepress-multilingual-cms/menu/languages.php','sitepress-multilingual-cms/menu/menus-sync.php');
   changed to:
   remove_submenu_page('sitepress-multilingual-cms/menu/languages.php','sitepress-multilingual-cms/menu/menu-sync/menus-sync.php');
2.  add_action( 'admin_head-nav-menus.php', 'so_hide_wpml_sync_link' );
   didn't found 'admin_head-nav-menus.php' file in my WPML so tried adding here few similar files that I found.

nothing worked, so contacted you :)

**Comment by senlin** [comment]
Thanks very much, will see what I can do! Give me a day orso.

**Comment by skeptikas** [comment]
Noo problem, if need help on running some code tests on xampp, just let me know.

**Comment by senlin** [comment]
Found the culprit, just needed to add menu-sync in the remove_submenu_page() function as you will see on [line 171](https://github.com/senlin/so-remove-wpml-menu-sync/blob/master/so-remove-wpml-menu-sync.php#L171)
Thanks again for filing this bug report!
Cheers,
Piet
